# Generated by Django 4.1.7 on 2023-04-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='status',
            field=models.CharField(choices=[('1', 'on'), ('2', 'off'), ('3', 'unavailable')], max_length=1),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('1', 'sensor'), ('2', 'light'), ('3', 'switch'), ('4', 'multimedia'), ('5', 'air_conditioner')], max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
